version: '3.8'

services:
  user_service:
    build:
      context: ./user_service
    container_name: booking_system_user_service  # Assign a specific name to the container
    ports:
      - "8000:8000"
    volumes:
      - ./user_service:/app
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: booking_system_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
